//
// Created by holmes on 2021/4/1.
//

#ifndef LOWRANKDESCENDC_HEDGEALGORITHM_H
#define LOWRANKDESCENDC_HEDGEALGORITHM_H

void HedgeMain(int INPUT_DIMENSION_LOWER, int  INPUT_DIMENSION_UPPER, int ROUND);

#endif //LOWRANKDESCENDC_HEDGEALGORITHM_H

