//
// Created by holmes on 2021/4/1.
//

#ifndef LOWRANKDESCENDC_MIRRORDESCEND_H
#define LOWRANKDESCENDC_MIRRORDESCEND_H

void MirrorDescendMain(int INPUT_DIMENSION_LOWER, int INPUT_DIMENSION_UPPER, int INPUT_RANK, int ROUND);

#endif //LOWRANKDESCENDC_MIRRORDESCEND_H
